// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "posts-fnesev",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api06d2a5da",
            "endpoint": "https://6aauaumg23.execute-api.us-west-2.amazonaws.com/fnesev",
            "region": "us-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-2:0e00e4ef-33b6-4d2c-884d-bde10cfbcf12",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5yI1A974i",
    "aws_user_pools_web_client_id": "603f83vrmjmecu8dlsmc5t2uch",
    "oauth": {}
};


export default awsmobile;
